---
# Repository configuration for wetransform managed repositories

# Reference presets that should apply to this repository
presets:
  - renovate

# Additional required checks
required_checks:
  - check-update
