---
name: renovate

on:
  workflow_dispatch:
    inputs:
      dryRun:
        type: boolean
        description: "Dry-Run"
      logLevel:
        type: choice
        description: "Log-Level"
        default: debug
        options:
          - info
          - debug
          - trace
  push:
    branches:
      - master
      - "!renovate/*"
  schedule:
    - cron: "0 0,2,4 * * 0"

env:
  # https://docs.renovatebot.com/troubleshooting/#log-debug-levels
  LOG_LEVEL: "${{ inputs.logLevel || 'debug' }}"
  # https://docs.renovatebot.com/self-hosted-configuration/#repositories
  RENOVATE_REPOSITORIES: ${{ github.repository }}
  # https://docs.renovatebot.com/self-hosted-configuration/#username
  RENOVATE_USERNAME: ${{ github.repository_owner }}
  # https://docs.renovatebot.com/configuration-options/#platformcommit
  RENOVATE_PLATFORM_COMMIT: "true"
  # https://docs.renovatebot.com/self-hosted-configuration/#dryrun
  # Run renovate in dry-run mode if executed in branches other than master - prevents versions in PRs/branches from being updated
  RENOVATE_DRY_RUN: "${{ inputs.dryRun || ( github.head_ref || github.ref_name ) != 'master' || false }}"
  # Renovate Automerge
  # RENOVATE_AUTOMERGE_TYPE: "branch" # auto-merge without creating PR (requires checks to run on renovate branches)
  # RENOVATE_AUTOMERGE: "true"

permissions: read-all

jobs:
  renovate:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

      - uses: actions/create-github-app-token@7bfa3a4717ef143a604ee0a99d859b8886a96d00 # v1.9.3
        id: app-token
        with:
          # see https://github.com/renovatebot/renovate/blob/47c8501c412c2f53f61ca292a5039f5939c32c5d/lib/modules/platform/github/readme.md?plain=1#L28
          app-id: ${{ secrets.WE_RENOVATE_GITHUB_APP_ID }}
          private-key: "${{ secrets.WE_RENOVATE_GITHUB_PRIVATE_KEY }}"

      - name: 💡 Self-hosted Renovate
        uses: renovatebot/github-action@2d90417499f45ff78a09586f7b9874b19817dba3 # v40.1.0
        with:
          token: "${{ steps.app-token.outputs.token }}"
